In [1]:
from __future__ import print_function
import torch

In [12]:
torch.empty(5,5)
torch.rand(5,5)
torch.zeros(5,5)
a=torch.tensor([4,6])
a=a.new_ones(10,5,dtype=torch.double)

In [19]:
b=torch.rand_like(a)
b.size()

torch.Size([10, 5])

In [32]:
c=torch.rand_like(a)
torch.add(a,b,out=c)
a.add_(b)
a[1][1].item()
a.numpy()

array([[5.77583084, 2.21066671, 6.47369024, 6.2603398 , 2.82845496],
       [3.59569188, 4.52329662, 5.25146034, 9.71043628, 5.34848756],
       [2.2527669 , 5.70217441, 4.9934606 , 7.43938243, 5.10185519],
       [6.60722248, 9.41621955, 4.91321215, 8.18072665, 9.31519693],
       [6.38175575, 5.71784393, 7.57277105, 2.24845758, 9.61079911],
       [1.50935708, 8.27026484, 1.65329134, 5.09999114, 6.77883259],
       [6.80905647, 3.84825765, 2.39093678, 6.72307031, 5.18048402],
       [1.51699584, 6.34165583, 1.6708276 , 1.57038421, 4.10134393],
       [3.49737778, 4.47350015, 1.6875679 , 4.8117802 , 3.05467741],
       [5.99688088, 3.12803123, 4.47137153, 7.84651895, 1.06433793]])

In [179]:
x = torch.ones(2, 1, requires_grad=True)
y = torch.tensor([5.0,6.0],requires_grad=True)
print('x=',x,'\n y=',y)

x= tensor([[1.],
        [1.]], requires_grad=True) 
 y= tensor([5., 6.], requires_grad=True)


In [180]:
z = x**3
a =y**4
out=z.mean()+a.mean()

In [181]:
out.backward()

In [182]:
print('out to x derivative',x.grad,'\n out to y derivative',y.grad)

out to x derivative tensor([[1.5000],
        [1.5000]]) 
 out to y derivative tensor([250., 432.])


In [38]:
print(y.grad_fn)

In [68]:
z = y * y * 3*2
out = z.mean()

#print(z, out)
z
#out

tensor([[54., 54.],
        [54., 54.]], grad_fn=<MulBackward0>)

In [60]:
a = torch.randn(2, 2)
a
#a = ((a * 3) / (a - 1))
#print(a.requires_grad)
a.requires_grad_(True)
#print(a.requires_grad)
#b = (a * a).sum()
#print(b.grad_fn)
#
print(a)

tensor([[-1.5296, -1.1548],
        [ 1.9409, -1.2178]])


In [64]:
a*a

tensor([[2.3398, 1.3335],
        [3.7672, 1.4830]])

In [51]:
out.backward()

In [90]:
x.grad